# Generated by Django 5.2.6 on 2025-09-15 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshorten',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='urlshorten',
            name='Short_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
